version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: alle-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  alle:
    build: .
    container_name: alle
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      WS_URL: "0.0.0.0:8080"
      LOG_LEVEL: "alle=info,info"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
